language: cpp
sudo: required
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
env:
    - CMAKE_PARAMETERS="-DUseQtFive=ON"
    - CMAKE_PARAMETERS="-DUseQtFive=OFF"
#    - BUILDSYSTEM=outside
matrix:
  fast_finish: true
  allow_failures:
    - env: CMAKE_PARAMETERS="-DUseQtFive=ON"
  exclude:
    - os: osx
      env: CMAKE_PARAMETERS="-DUseQtFive=ON"
    - os: osx
      compiler: gcc
install:
 - _travis/install_dependencies
 - _travis/compile
script: _travis/test
