language: cpp
compiler: gcc
sudo: false
cache: ccache
# define dependencies as q4dep and q5dep
qt4_deps: &q4dep
    - libboost-program-options-dev
    - libboost-test-dev
    - pkg-config
    - xvfb
    - xauth
    - libpoppler-qt4-dev
    - texlive-latex-recommended
    - texlive-pictures
    - latex-beamer
    - xserver-xorg-video-dummy
qt5_deps: &q5dep
    - libboost-program-options-dev
    - libboost-test-dev
    - pkg-config
    - xvfb
    - xauth
    - libpoppler-qt5-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - texlive-latex-recommended
    - texlive-pictures
    - latex-beamer
    - xserver-xorg-video-dummy
addons:
    apt:
        packages: *q4dep
env: QT_VERSION=4
# Only build master branch on push, other branches will get built when
# they are turned into pull-requests
branches:
    only:
        - master
        - /^test-.*$/
# Build matrix.
#
# The first (implicit) build will be
# qt4/gcc/container-based (precise)
#
# additional builds specified are
# 2. qt4/clang/container (precise)
# 3. qt5/gcc/gce (sudo/trusty)
# 4. qt5/clang/gce (sudo/trusty)
# 5. osx/clang
matrix:
    include:
        - compiler: clang
        - dist: trusty
          sudo: required
          env: QT_VERSION=5
          compiler: gcc
          addons:
              apt:
                  packages: *q5dep
        - dist: trusty
          sudo: required
          env: QT_VERSION=5
          compiler: clang
          addons:
              apt:
                  packages: *q5dep
        - os: osx
          compiler: clang
          before_install: _travis/osx-install-dependencies
install:
    - _travis/configure
    - make -C build
script: _travis/test
after_success:
    - pip install --user codecov
    - >
        if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
          ~/Library/Python/*/bin/codecov ;
        elif [[ "$CXX" == "clang++" ]] ; then
          ~/.local/bin/codecov --gcov-exec llvm-cov ;
        else
          ~/.local/bin/codecov ;
        fi
