exclude:
  - vendor
  - Gemfile
  - Makefile

markdown: redcarpet
redcarpet:
  extensions:
    - autolink
    - with_toc_data

# mimick github
# changeable
highlighter: pygments

# mimick github
# fixed
safe: true
lsi: false
source: .

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
